package com.ahuo.spring.entity;

public class User extends UserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.height
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weight
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.blog
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String blog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headImage
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String headimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.photo
     *
     * @return the value of user.photo
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.photo
     *
     * @param photo the value for user.photo
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.height
     *
     * @return the value of user.height
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.height
     *
     * @param height the value for user.height
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weight
     *
     * @return the value of user.weight
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weight
     *
     * @param weight the value for user.weight
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.blog
     *
     * @return the value of user.blog
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.blog
     *
     * @param blog the value for user.blog
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headImage
     *
     * @return the value of user.headImage
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getHeadimage() {
        return headimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headImage
     *
     * @param headimage the value for user.headImage
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setHeadimage(String headimage) {
        this.headimage = headimage == null ? null : headimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu May 25 17:10:32 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}